version: '3.8'

services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - LOAD_ONLY=en,es,fr,de,it,pt,ru  # Limited languages to save space
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  doxulate:
    build: .
    container_name: doxulate
    ports:
      - "8000:8000"
    environment:
      - LIBRETRANSLATE_URL=http://libretranslate:5000 
    depends_on:
      libretranslate:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./templates:/app/templates
      - ./static:/app/static
