app = "libretranslate"
primary_region = "cdg"

[env]
  LOAD_ONLY = "en,ar,es,fr,de,it,pt,ru"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
